extra-package-dbs: []
packages:
  - burn
  - burn-cli
  - burn-gtk
  - peridot
extra-deps:
  - bloodhound-0.16.0.0
  - containers-0.5.11.0
  - binary-0.8.7.0
  - gtk3-0.15.1
  - cairo-0.13.6.0
  - gio-0.13.6.0
  - glib-0.13.7.0
  - gtk2hs-buildtools-0.13.5.0
  - pango-0.13.6.0

resolver: lts-13.28
nix:
  packages: [pkgconfig, zlib, cairo, glib, pango, gnome3.gtk3]
  pure: true
