extra-package-dbs: []
packages:
  - burn
  - burn-cli
  - burn-gtk
  - peridot
extra-deps:
  - aeson-2.1.0.0
  - cassava-0.5.2.0
  - data-default-0.7.1.1
  - dependent-map-0.4.0.0
  - dependent-sum-0.7.1.0
  - dependent-sum-template-0.1.1.1
  - dlist-1.0
  - foldl-1.4.12
  - formatting-7.1.3
  - gtk3-0.15.7
  - http-client-0.7.11
  - inflections-0.4.0.6
  - lens-5.1.1
  - optparse-applicative-0.17.0.0
  - profunctors-5.6.2
  - servant-0.19
  - servant-client-0.19
  - servant-server-0.19.1
  - statistics-0.16.1.0
  - transformers-base-0.4.6
  - vinyl-0.14.3
  - warp-3.3.21
  - OneTuple-0.3.1
  - Only-0.1
  - QuickCheck-2.14.2
  - ansi-wl-pprint-0.6.9
  - assoc-1.0.2
  - async-2.2.4
  - attoparsec-0.14.4
  - auto-update-0.1.6
  - base-compat-0.12.1
  - base-compat-batteries-0.12.1
  - base-orphans-0.8.6
  - base64-bytestring-1.2.1.0
  - bifunctors-5.5.12
  - blaze-builder-0.4.2.2
  - bsb-http-chunked-0.0.0.4
  - call-stack-0.4.0
  - case-insensitive-1.2.1.0
  - clock-0.8.3
  - comonad-5.0.8
  - constraints-0.13.4
  - constraints-extras-0.3.2.1
  - contravariant-1.5.5
  - cookie-0.4.5
  - data-default-class-0.1.2.0
  - data-default-instances-containers-0.0.1
  - data-default-instances-dlist-0.0.1
  - data-default-instances-old-locale-0.0.1
  - data-fix-0.3.2
  - dense-linear-algebra-0.1.0.0
  - distributive-0.6.2.1
  - double-conversion-2.0.4.1
  - free-5.1.8
  - generically-0.1
  - http-api-data-0.4.3
  - http-date-0.0.11
  - http-media-0.8.0.0
  - http-types-0.12.3
  - http2-3.0.3
  - indexed-traversable-0.1.2
  - indexed-traversable-instances-0.1.1
  - iproute-1.7.12
  - kan-extensions-5.2.4
  - math-functions-0.3.4.2
  - megaparsec-9.2.1
  - mime-types-0.1.0.9
  - mmorph-1.2.0
  - monad-control-1.0.3.1
  - mwc-random-0.15.0.2
  - network-3.1.2.7
  - network-uri-2.6.4.1
  - old-locale-1.0.0.7
  - parallel-3.2.2.0
  - reflection-2.1.6
  - resourcet-1.2.5
  - scientific-0.3.7.0
  - semialign-1.2.0.1
  - semigroupoids-5.3.7
  - servant-client-core-0.19
  - simple-sendfile-0.2.30
  - singleton-bool-0.1.6
  - some-1.0.3
  - sop-core-0.5.0.2
  - streaming-commons-0.2.2.4
  - strict-0.4.0.1
  - string-conversions-0.4.0.1
  - tagged-0.8.6.1
  - text-short-0.1.5
  - th-abstraction-0.4.3.0
  - th-extras-0.0.0.6
  - these-1.1.1.1
  - time-compat-1.9.6.1
  - time-manager-0.0.0
  - transformers-compat-0.7.1
  - unix-compat-0.6
  - unliftio-0.2.22.0
  - unordered-containers-0.2.19.1
  - uuid-types-1.0.5
  - vault-0.3.1.5
  - vector-algorithms-0.8.0.4
  - vector-binary-instances-0.2.5.2
  - vector-th-unbox-0.2.2
  - wai-3.2.3
  - wai-app-static-3.1.7.4
  - witherable-0.4.2
  - word8-0.1.3
  - x509-1.7.7
  - StateVar-1.2.2
  - adjunctions-4.4.1
  - ansi-terminal-0.11.3
  - appar-0.1.8
  - asn1-encoding-0.9.6
  - asn1-parse-0.9.5
  - asn1-types-0.3.4
  - attoparsec-iso8601-1.0.2.1
  - blaze-html-0.9.1.2
  - blaze-markup-0.8.2.8
  - boring-0.2
  - byteorder-1.0.4
  - cryptonite-0.30
  - dec-0.0.4
  - file-embed-0.0.15.0
  - hourglass-0.2.12
  - integer-logarithms-1.0.3.1
  - invariant-0.5.6
  - memory-0.17.0
  - network-byte-order-0.1.6
  - parser-combinators-1.3.0
  - pem-0.2.4
  - psqueues-0.2.7.3
  - safe-0.3.19
  - syb-0.7.2.1
  - th-compat-0.1.3
  - type-equality-1
  - unix-time-0.4.7
  - unliftio-core-0.2.0.1
  - wai-extra-3.1.12.1
  - zlib-0.6.3.0
  - HUnit-1.6.2.0
  - basement-0.0.14
  - colour-2.3.6
  - fast-logger-3.1.1
  - old-time-1.1.0.3
  - semigroups-0.20
  - tasty-1.4.2.3
  - tasty-hunit-0.10.0.3
  - void-0.7.3
  - wai-logger-2.4.0
  - cabal-doctest-1.0.9
  - easy-file-0.2.2
  - unbounded-delays-0.1.1.1
  - wcwidth-0.0.2
  - cairo-0.13.8.2
  - gio-0.13.8.2
  - glib-0.13.8.2
  - gtk2hs-buildtools-0.13.8.3
  - hashable-1.4.0.2
  - pango-0.13.8.2
  - primitive-0.7.4.0
  - random-1.2.1.1
  - splitmix-0.1.0.4
  - utf8-string-1.0.2
  - vector-0.12.3.1
  - alex-3.2.7.1
  - happy-1.20.0
  - hashtables-1.3

resolver: ghc-8.10.7
nix:
  # shell-file: shell.nix
  packages: [pkgconfig, zlib, cairo, glib, pango, gtk3]
  pure: true
