extra-package-dbs: []
packages:
  - burn
  - burn-cli
  - burn-gtk
  - peridot
extra-deps:
  - http-api-data-0.3.4
  - optparse-applicative-0.13.1.0
  - servant-0.9.1.1
  - servant-client-0.9.1.1
  - servant-server-0.9.1.1
resolver: lts-6.27
