extra-package-dbs: []
packages:
  - burn
  - burn-cli
  - burn-gtk
  # - peridot
extra-deps:
  - gtk3-0.15.7
  - cairo-0.13.8.2
  - gio-0.13.8.2
  - glib-0.13.8.2
  - pango-0.13.8.2
  - bloodhound-0.21.0.0

resolver: lts-19.10
nix:
  # shell-file: shell.nix
  packages: [pkgconfig, zlib, cairo, glib, pango, gtk3]
  pure: true
